requires 'Carp', '1.50';
requires 'Date::Parse', '2.33';
requires 'Digest::SHA', '6.02';
requires 'File::Find';
requires 'File::Path', '2.18';
requires 'FindBin', '1.52';
requires 'IO::Socket::SSL', '2.069';
requires 'Mojolicious', '9.01';
requires 'Readonly::Tiny', '4';
requires 'Time::HiRes', '1.9764';
requires 'Try::Tiny', '0.30';
requires 'Util::CommandLine', '1.06';
requires 'WWW::Mechanize::PhantomJS', '0.24';
requires 'YAML::XS', '0.82';
requires 'exact', '1.17';
